version: "3.8"
services:
  lx:
    container_name: lx-server
    build: .
    ports:
      - "9763:9763"
    volumes:
      - .:/app
    environment:
        TZ: 'Asia/Shanghai'
    restart: always
networks:
  default:
    
