
name: Build Release

on:
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout git repo
        uses: actions/checkout@v2
      
      - name: Setup Python 3.11
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'
      
      - name: Install pyinstaller
        run: python -m pip install pyinstaller
      
      - name: Install dependencies
        run: python -m pip install -r ./requirements.txt
      
      - name: Build EXE
        run: python build.py build release
      
      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: windows
          path: ./dist

  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout git repo
        uses: actions/checkout@v2

      - name: Setup Python 3.11
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Install pyinstaller
        run: python -m pip install pyinstaller
      
      - name: Install dependencies
        run: python -m pip install -r ./requirements.txt
        
      - name: Build Executable
        run: python build.py build release
        
      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: linux
          path: ./dist
